[colors.primary]
background = "0x000000"
foreground = "0xffffff"
 
[cursor]
style = "Beam"
unfocused_hollow = true
 
[font]
size = 12.0
 
[font.bold]
family = "Fira Code"
style = "Bold"
 
[font.glyph_offset]
x = 0
y = 0
 
[font.italic]
family = "Fira Code"
style = "Italic"
 
[font.normal]
family = "Fira Code"
style = "Regular"
 
[font.offset]
x = 0
y = 0
 
[scrolling]
history = 10000
multiplier = 3
 
[window]
decorations = "full"
dynamic_title = true
opacity = 0.85
startup_mode = "Windowed"
 
[window.dimensions]
columns = 120
lines = 35
 
[window.padding]
x = 10
y = 10
